# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=50)),
                ('auth_token', models.CharField(max_length=50)),
                ('from_no', models.CharField(max_length=30)),
                ('to_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nisha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('snooze', models.BooleanField(default=False)),
                ('repeat_time', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
